// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dollarToPokemon.proto

package converters

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Mensagem de Request
type Request struct {
	DollarInReais        string   `protobuf:"bytes,1,opt,name=DollarInReais,proto3" json:"DollarInReais,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_267c6bb674b6c3bd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDollarInReais() string {
	if m != nil {
		return m.DollarInReais
	}
	return ""
}

//Mensagem de resposta
type Reply struct {
	PokemonName          string   `protobuf:"bytes,1,opt,name=PokemonName,proto3" json:"PokemonName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_267c6bb674b6c3bd, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetPokemonName() string {
	if m != nil {
		return m.PokemonName
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "converters.Request")
	proto.RegisterType((*Reply)(nil), "converters.Reply")
}

func init() {
	proto.RegisterFile("dollarToPokemon.proto", fileDescriptor_267c6bb674b6c3bd)
}

var fileDescriptor_267c6bb674b6c3bd = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xc9, 0xcf, 0xc9,
	0x49, 0x2c, 0x0a, 0xc9, 0x0f, 0xc8, 0xcf, 0x4e, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x4a, 0xce, 0xcf, 0x2b, 0x4b, 0x2d, 0x2a, 0x49, 0x2d, 0x2a, 0x56, 0xd2, 0xe7,
	0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe1, 0xe2, 0x75, 0x01, 0xab, 0xf7,
	0xcc, 0x0b, 0x4a, 0x4d, 0xcc, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x15, 0x54,
	0xd2, 0xe4, 0x62, 0x0d, 0x4a, 0x2d, 0xc8, 0xa9, 0x14, 0x52, 0xe0, 0xe2, 0x86, 0x1a, 0xeb, 0x97,
	0x98, 0x9b, 0x0a, 0x55, 0x8c, 0x2c, 0x64, 0xe4, 0xca, 0xc5, 0xee, 0x5e, 0x94, 0x9a, 0x5a, 0x92,
	0x5a, 0x24, 0x64, 0xc5, 0x25, 0xe0, 0x0c, 0xb1, 0x14, 0xee, 0x18, 0x21, 0x61, 0x3d, 0x84, 0x3b,
	0xf4, 0xa0, 0x8e, 0x90, 0x12, 0x44, 0x15, 0x2c, 0xc8, 0xa9, 0x4c, 0x62, 0x03, 0xbb, 0xda, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x42, 0xeb, 0x98, 0x03, 0xce, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	ConvertToPokemon(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) ConvertToPokemon(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/converters.Greeter/ConvertToPokemon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	ConvertToPokemon(context.Context, *Request) (*Reply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) ConvertToPokemon(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToPokemon not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_ConvertToPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ConvertToPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/converters.Greeter/ConvertToPokemon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ConvertToPokemon(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "converters.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToPokemon",
			Handler:    _Greeter_ConvertToPokemon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dollarToPokemon.proto",
}
